blank_issues_enabled: false
contact_links:
  - name: "Helm 4: Plugin install won't work"
    url: https://github.com/jkroepke/helm-secrets/wiki/Installation
    about: helm plugin install has been changed in Helm 4. Please see docs.
